### ISSUE TITLE
Brainstorming de aplicaciones

### ISSUE THREAD

**Issue by facundoq** [midusi/proyecto2019#7]
Discutamos idesa para las aplicaciones.

1) Simple detector de emociones. Sin tracking. Con varios usuarios en tele grande o uno solo en celular.
2) Idem con atributos.
3) Generador automático de avatar en base a atributos (y emociones) . Sin tracking. Con varios usuarios en tele grande o uno solo en celular.
4) "actuá las N emociones". Un solo usuario, trackeo (más complejo en tele grande), app con estado.
5) .....

**Comment by okason97** [comment]
Me interesa la idea de implementar tracking, la aplicacion se veria mas limpia, y usando yolo con recurrencia no perderia mucha performance (puede ser un problema para muchas caras).
Me re copa la idea de generacion de avatares también.

**Comment by facundoq** [comment]
Lo del tracking está bueno pero no es una aplicación :D

**Comment by FrancoRonchetti** [comment]
Para mi está bueno el tracking. Creo que se podrían mostrar las
probabilidades de todas las "emociones" y en todo caso encender más fuerte
la ganadora....
Pero me imagino que debe estar bueno que diga que tu cara (yo haría una
sola cara a priori) tenga "80% de probabilidad de estar triste" y "15%
alegre", etc...

**Comment by okason97** [comment]
La idea que propuse hoy es la de hacer un juego en el que se intente lograr el mayor puntaje de una emocion, intentando acercarse al 1 de probabilidad.
Despues de apretar un boton se captura la cara de la persona y en tiempo real se muestran las probabilidades (pueden mostrarse con barras para que se vea mas claro). Despues de un tiempo se puede mostrar el promedio de la mayor probabilidad.
